### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by kytwb** [nortxort/nortbot#17]
Command: `!bs ░░░░█----------------`

```
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/nortbot/tinychat.py", line 163, in connect
    self._listener()
  File "/root/nortbot/tinychat.py", line 212, in _listener
    self.dispatch(event, json_data)
  File "/root/nortbot/tinychat.py", line 223, in dispatch
    self._process_event(event, method, event_data)
  File "/root/nortbot/tinychat.py", line 216, in _process_event
    pe.process()
  File "/root/nortbot/_process_event.py", line 71, in process
    self._process_msg()
  File "/root/nortbot/_process_event.py", line 138, in _process_msg
    self._client.run_method(self._method, *(user, msg))
  File "/root/nortbot/tinychat.py", line 233, in run_method
    func(*args, **kwargs)
  File "/root/nortbot/bot.py", line 173, in on_msg
    ch.handle()
  File "/root/nortbot/handlers/command.py", line 59, in handle
    self._handle_command(cmd, cmd_arg)
  File "/root/nortbot/handlers/command.py", line 253, in _handle_command
    self.do_bad_string(cmd_arg)
  File "/root/nortbot/handlers/command.py", line 1317, in do_bad_string
    self._conf.STRING_BANS_FILE_NAME, bad_string)
  File "/root/nortbot/util/file_handler.py", line 74, in writer
    f.write(write_this + '\n')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
```

**Comment by Technetium1** [comment]
This is expected. Unicode is not supported yet.

**Comment by kytwb** [comment]
No problems, just reporting 👍
