### ISSUE TITLE
Traceback modular issues

### ISSUE THREAD

**Issue by joemisfit** [nortxort/nortbot#20]
Hello Nort,

I was wondering if I could get a little assistance with your bot as I'm experiencing some traceback errors, and I realize one has to do with a password issue, which the password has been changed, however I can't figure out the other issues. Attached is a screenshot.

![Screenshot_2](https://user-images.githubusercontent.com/20868143/57203527-c04a8500-6f65-11e9-9132-a6a519910596.png)

P.s. Don't mind the NortyBot thing, I have a few versions and that's just to try a new instance to check for errors.

**Comment by Autotonic** [comment]
This is due to ConfigParser failing to parse `%` and python being bad.
```sh
aida@uberry:~$ cat test.ini
[a]
Test=%ABC

aida@uberry:~$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```
```py
>>> import configparser
>>> config = configparser.ConfigParser()
>>> config.read("test.ini")
['test.ini']
>>> config.get("a", "Test")
'%ABC'

>>> config = configparser.SafeConfigParser()
>>> config.read("test.ini")
['test.ini']
>>> config.get("a", "Test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/ConfigParser.py", line 623, in get
    return self._interpolate(section, option, value, d)
  File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib/python2.7/ConfigParser.py", line 732, in _interpolate_some
    "'%%' must be followed by '%%' or '(', found: %r" % (rest,))
ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%ABC'
```
To solve this you need to escape `%` with `%%` or remove `%` from the whatever you're using it in.
```sh
aida@uberry:~$ cat test.ini
[a]
Test=%%ABC

aida@uberry:~$ python2
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```
```py
>>> import configparser
>>> config = configparser.SafeConfigParser()
>>> config.read("test.ini")
['test.ini']
>>> config.get("a", "Test")
'%ABC'
```

**Comment by joemisfit** [comment]
Gotcha, it was apart of a password, also I noticed you made a pull request, were you going to by chance make a bat start file for the bot?

**Comment by Autotonic** [comment]
Doesn't really need a bat file to start it, but something like
```bat
C:\Python27\python.exe C:\Users\Joe\Documents\NortyBot-Dev\nortbot.py
```
should work for you

**Comment by Autotonic** [comment]
Solved with #19 

https://docs.python.org/2/library/configparser.html?highlight=configparser#ConfigParser.ConfigParser.get

**Comment by Technetium1** [comment]
If you are going to have a batch file to start it, make sure you cd to where nortbot.py is first, rather than just call it directly.

**Comment by joemisfit** [comment]
Gotcha, I basically already do that.
