### ISSUE TITLE
AttributeError: 'list' object has no attribute 'start'

### ISSUE THREAD

**Issue by kytwb** [nortxort/nortbot#22]
```
[06:39:06:237] <redacted>: !cm
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/nortbot/tinychat.py", line 163, in connect
    self._listener()
  File "/root/nortbot/tinychat.py", line 212, in _listener
    self.dispatch(event, json_data)
  File "/root/nortbot/tinychat.py", line 223, in dispatch
    self._process_event(event, method, event_data)
  File "/root/nortbot/tinychat.py", line 216, in _process_event
    pe.process()
  File "/root/nortbot/_process_event.py", line 71, in process
    self._process_msg()
  File "/root/nortbot/_process_event.py", line 138, in _process_msg
    self._client.run_method(self._method, *(user, msg))
  File "/root/nortbot/tinychat.py", line 233, in run_method
    func(*args, **kwargs)
  File "/root/nortbot/bot.py", line 173, in on_msg
    ch.handle()
  File "/root/nortbot/handlers/command.py", line 59, in handle
    self._handle_command(cmd, cmd_arg)
  File "/root/nortbot/handlers/command.py", line 197, in _handle_command
    self.do_close_media()
  File "/root/nortbot/handlers/command.py", line 962, in do_close_media
    if self._playlist.has_active_track:
  File "/root/nortbot/util/tracklist.py", line 84, in has_active_track
    if self.elapsed == 0:
  File "/root/nortbot/util/tracklist.py", line 101, in elapsed
    elapsed = time.time() - self.current_track.start
AttributeError: 'list' object has no attribute 'start'
```

**Comment by Autotonic** [comment]
Can you give a bit more detail, like did a moderator close the video before this

**Comment by kytwb** [comment]
Ah my bad, I just added the last command I saw in the log before the crash, didn't pay attention at the commands that were sent right before the `!cm`. Anyway, I think this can be gracefully handled independently from what were the previous commands, no? WDYT?

**Comment by nortxort** [comment]
I am a little puzzled about this. `current_track` should not be a list, but rather a Track object. I need more info. Like what leads it to happen? what command's were used prior to it happening? debug log?

**Comment by kytwb** [comment]
I haven't kept the log for this crash, will update with mor infos if I see it again.

**Comment by Autotonic** [comment]
Need help recreating this issue

**Comment by kytwb** [comment]
Haven't seen it happen again.

**Comment by Autotonic** [comment]
Reckon we should close?

**Comment by kytwb** [comment]
Yep, let's reopen if it re-happen and will make sure to come with more logs.

**Comment by imtammer** [comment]
im experiencing this issues as well:

[07:28:28:975] T00MuchSalt: !yt https://youtu.be/6JBpr5Rqdtg                    
'list' object has no attribute 'start'                                          
[07:28:30:891] Geek: !yt buyy                                                   
[07:28:31:105] Anicrow: !yt this is america                                     
'list' object has no attribute 'start'                                          
'list' object has no attribute 'start'

**Comment by Autotonic** [comment]
@imtammer can you go back through your logs for the couple of commands and paste them, ensuring to remove any info that may be sensitive to others.

**Comment by imtammer** [comment]
i turned on logging as well in config, restart bot, and voila it began to work...will keep you posted if it crops up again.

**Comment by Technetium1** [comment]
This is probably fixed in https://github.com/nortxort/nortbot/commit/4362a9934fd02d04fa1d0da48089c2ecea9612bb

**Comment by Technetium1** [comment]
Does not seem to be a problem. Comment if this needs reopened.
